import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { createGpsProjector } from '../src/map/gps.ts';
import { createGpsTracker, gpsStaleAfterMs } from '../src/map/gpsTracking.ts';

const readJson = (path) => JSON.parse(readFileSync(new URL(path, import.meta.url), 'utf8'));
const pack = readJson('../public/map-packs/current/map-pack.json');
const references = readJson('./fixtures/gps-reference.json');
const project = createGpsProjector(pack);
const fix = (reference, timestamp = 1_000_000, accuracy = 5) => ({
  timestamp,
  coords: { latitude: reference.latitude, longitude: reference.longitude, accuracy }
});

// Fixed reference coordinates from the audit, not values generated by the
// function under test. They catch both reflection and geographic interpolation.
for (const reference of references) {
  test(`${reference.name} projects to the expected image location`, () => {
    const result = project({ ...reference, accuracyMeters: 5 });
    assert.ok(Math.hypot(...result.point.map((v, i) => v - reference.expected[i])) < 0.01,
      `${result.point} should be ${reference.expected}`);
    assert.equal(result.inside, true);
  });
}

test('moving north increases Leaflet Y, not image-row Y', () => {
  const north = project({ ...references.find(p => p.name === 'North test'), accuracyMeters: 5 });
  const south = project({ ...references.find(p => p.name === 'South test'), accuracyMeters: 5 });
  assert.ok(Math.abs(north.point[0] - south.point[0] - 3000) < 0.01);
  assert.ok(Math.abs(north.point[1] - south.point[1]) < 0.01);
});

test('geographic envelope has no effect on projection', () => {
  const changed = createGpsProjector({ ...pack, gpsBounds: undefined });
  assert.deepEqual(changed({ ...references[1], accuracyMeters: 5 }), project({ ...references[1], accuracyMeters: 5 }));
});

test('origin and pixel size come from metadata, not hardcoded current-map values', () => {
  const changed = createGpsProjector({
    ...pack, pixelSizeMeters: 0.4,
    georeference: { ...pack.georeference, westEastingMeters: 688900, southNorthingMeters: 4962800 }
  });
  const result = changed({ ...references[0], accuracyMeters: 0 });
  assert.ok(Math.abs(result.point[0] - 500) < 0.01);
  assert.ok(Math.abs(result.point[1] - 250) < 0.01);
});

test('outside fixes remain outside instead of snapping onto the map', () => {
  const result = project({ latitude: 44.82, longitude: -78.60, accuracyMeters: 10 });
  assert.equal(result.inside, false);
  assert.ok(result.point[0] > pack.height);
});

test('invalid coordinates and uncertainty cannot produce a marker', () => {
  for (const overrides of [{latitude:NaN}, {latitude:91}, {longitude:181}, {longitude:Infinity}, {accuracyMeters:-1}, {accuracyMeters:NaN}]) {
    assert.throws(() => project({ ...references[0], accuracyMeters:5, ...overrides }), /Invalid GPS/);
  }
});

test('missing or invalid georeferencing fails instead of falling back to bounds', () => {
  for (const bad of [
    { ...pack, georeference: undefined },
    { ...pack, pixelSizeMeters: 0 },
    { ...pack, width: NaN },
    { ...pack, georeference: { ...pack.georeference, southNorthingMeters: NaN } }
  ]) assert.throws(() => createGpsProjector(bad), /georeference/);
});

function trackingHarness() {
  const updates = [], statuses = [], reports = [];
  const tracker = createGpsTracker({
    setPosition(position) { updates.push(position); return position ? project(position) : null; },
    setStatus(message) { statuses.push(message); },
    report(...values) { reports.push(values); }
  });
  return { tracker, updates, statuses, reports };
}

test('tracker displays accuracy and reports projected diagnostics', () => {
  const h = trackingHarness();
  h.tracker.receive(fix(references[4], 1000, 12), 1000);
  assert.equal(h.statuses.at(-1), 'GPS ±12 m');
  assert.equal(h.reports.length, 1);
});

test('an old incoming fix never becomes a current marker', () => {
  const h = trackingHarness();
  h.tracker.receive(fix(references[4], 1000), 1000 + gpsStaleAfterMs + 1);
  assert.deepEqual(h.updates, [null]);
  assert.match(h.statuses.at(-1), /stale/);
});

test('a fix expires, is cleared once, and recovers on the next fresh fix', () => {
  const h = trackingHarness();
  h.tracker.receive(fix(references[4], 1000), 1000);
  h.tracker.checkFreshness(1000 + gpsStaleAfterMs);
  assert.notEqual(h.updates.at(-1), null);
  h.tracker.checkFreshness(1001 + gpsStaleAfterMs);
  assert.equal(h.updates.at(-1), null);
  h.tracker.checkFreshness(2000 + gpsStaleAfterMs);
  assert.equal(h.updates.length, 2);
  h.tracker.receive(fix(references[5], 100_000), 100_000);
  assert.notEqual(h.updates.at(-1), null);
  assert.equal(h.statuses.at(-1), 'GPS ±5 m');
});

test('GPS errors and invalid fixes clear a previous marker', () => {
  const h = trackingHarness();
  h.tracker.receive(fix(references[4], 1000), 1000);
  h.tracker.fail('Permission denied');
  assert.equal(h.updates.at(-1), null);
  assert.equal(h.statuses.at(-1), 'Permission denied');
  h.tracker.receive(fix({latitude:NaN, longitude:0}, 2000), 2000);
  assert.equal(h.updates.at(-1), null);
  assert.match(h.statuses.at(-1), /Invalid GPS/);
});

test('off-map fixes show an explicit status', () => {
  const h = trackingHarness();
  h.tracker.receive(fix({latitude:44.82, longitude:-78.60}, 1000), 1000);
  assert.match(h.statuses.at(-1), /^Outside this map/);
});
